---
version: '3.9'

services:
  frontend:
    image: ghcr.io/fosten/plone-pimaker-site-frontend:${STACK_PARAM:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://testing-pimaker-org_backend:8080/Plone
      RAZZLE_API_PATH: https://testing.pimaker.org
      RAZZLE_HOMEASSISTANT_API_HOST: ${RAZZLE_HOMEASSISTANT_API_HOST}
      RAZZLE_HOMEASSISTANT_API_PORT: ${RAZZLE_HOMEASSISTANT_API_PORT}
      RAZZLE_HOMEASSISTANT_ACCESS_TOKEN: ${RAZZLE_HOMEASSISTANT_ACCESS_TOKEN}
    depends_on:
      - backend
    networks:
      - traefik-public
      - traefik-testing_pimaker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == pimakerapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Service
        - traefik.http.services.testing_pimaker-frontend.loadbalancer.server.port=3000
        # Middlewares
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.testing_pimaker-frontend-auth.basicauth.users=testing:${TRAEFIK_HASHED_PASSWORD}
        # Routers
        ## / (Internal)
        - traefik.http.routers.testing_pimaker-frontend.rule=Host(`testing.pimaker.org`)
        - traefik.http.routers.testing_pimaker-frontend.entrypoints=https
        - traefik.http.routers.testing_pimaker-frontend.tls=true
        - traefik.http.routers.testing_pimaker-frontend.tls.certresolver=mydnschallenge
        - traefik.http.routers.testing_pimaker-frontend.service=testing_pimaker-frontend
        - traefik.http.routers.testing_pimaker-frontend.middlewares=testing_pimaker-frontend-auth

  backend:
    image: ghcr.io/fosten/plone-pimaker-site-backend:${STACK_PARAM:-latest}
    environment:
      RELSTORAGE_DSN: "dbname='${TESTING_DB_NAME:-plone}' user='${TESTING_DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}' port='${DB_PORT:-5432}'"
    networks:
      - traefik-public
      - traefik-testing_pimaker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == pimakerapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Services
        - traefik.http.services.testing_pimaker-backend.loadbalancer.server.port=8080
        # Middlewares
        ## VHM rewrite /++api++/
        - "traefik.http.middlewares.testing_pimaker-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.testing_pimaker-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/https/testing.pimaker.org/Plone/++api++/VirtualHostRoot$$1"
        ## VHM rewrite /ClassicUI/
        - "traefik.http.middlewares.testing_pimaker-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.testing_pimaker-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/https/testing.pimaker.org/Plone/VirtualHostRoot/_vh_ClassicUI$$1"
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.testing_pimaker-backend-auth.basicauth.users=admin:${TRAEFIK_HASHED_PASSWORD}

        # Routes
        ## /++api++ (Internal)
        - traefik.http.routers.testing_pimaker-backend-api.rule=Host(`testing.pimaker.org`) && PathPrefix(`/++api++`)
        - traefik.http.routers.testing_pimaker-backend-api.entrypoints=https
        - traefik.http.routers.testing_pimaker-backend-api.tls=true
        - traefik.http.routers.testing_pimaker-backend-api.service=testing_pimaker-backend
        - traefik.http.routers.testing_pimaker-backend-api.middlewares=gzip,testing_pimaker-backend-vhm-api
        ## /ClassicUI
        - traefik.http.routers.testing_pimaker-backend-classic.rule=Host(`testing.pimaker.org`) && PathPrefix(`/ClassicUI`)
        - traefik.http.routers.testing_pimaker-backend-classic.entrypoints=https
        - traefik.http.routers.testing_pimaker-backend-classic.tls=true
        - traefik.http.routers.testing_pimaker-backend-classic.service=testing_pimaker-backend
        - traefik.http.routers.testing_pimaker-backend-classic.middlewares=gzip,testing_pimaker-backend-auth,testing_pimaker-backend-vhm-classic

networks:
  traefik-public:
    external: true
  traefik-testing_pimaker:
    internal: true
    driver: overlay
