version: "3.3"
services:

  frontend:
    image: ghcr.io/fosten/plone-pimaker-site-frontend:latest
    networks:
      - traefik-public
      - traefik-testing_pimaker
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
      - "3014:3000"
    depends_on:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == pimakerapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # SERVICE
        - traefik.http.services.testing_pimaker-frontend.loadbalancer.server.port=3000
        # MIDDLEWARES
        ### ClassicUI Access Authentication
        - traefik.http.middlewares.testing_pimaker-frontend-auth.basicauth.users=admin:$$2y$$05$$hGP72w.Rgky4RK7FrN9km.UpdwwHqB8gJNp8TQ4s4qDK8LxjfISl6
        # HOSTS: Main
        - traefik.http.routers.testing_pimaker-frontend.rule=Host(`testing.pimaker.org`)
        - traefik.http.routers.testing_pimaker-frontend.entrypoints=websecure
        - traefik.http.routers.testing_pimaker-frontend.tls=true
        - traefik.http.routers.testing_pimaker-frontend.tls.certresolver=mydnschallenge
        - traefik.http.routers.testing_pimaker-frontend.service=testing_pimaker-frontend
        - traefik.http.routers.testing_pimaker-frontend.middlewares=gzip,testing_pimaker-frontend-auth

  backend:
    image: ghcr.io/fosten/plone-pimaker-site-backend:latest
    networks:
      - traefik-public
      - traefik-testing_pimaker
    environment:
      RELSTORAGE_DSN: "dbname='${TESTING_DB_NAME:-plone}' user='${TESTING_DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}'"
    ports:
      - "8094:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == pimakerapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # SERVICE
        - traefik.http.services.testing_pimaker-backend.loadbalancer.server.port=8080
        # MIDDLEWARES
        ### basic_auth Authentication ClassicUI & Zope
        - traefik.http.middlewares.testing_pimaker-backend-auth.basicauth.users=admin:$$2y$$05$$hGP72w.Rgky4RK7FrN9km.UpdwwHqB8gJNp8TQ4s4qDK8LxjfISl6
        - traefik.http.middlewares.testing_pimaker-zope-auth.basicauth.users=admin:$$2y$$05$$hGP72w.Rgky4RK7FrN9km.UpdwwHqB8gJNp8TQ4s4qDK8LxjfISl6
        ### Backend ++api++ VHM
        - "traefik.http.middlewares.testing_pimaker-vhm-cleanup.replacepathregex.regex=^/((\\+\\+api\\+\\+/){1,})($$|.*)"
        - "traefik.http.middlewares.testing_pimaker-vhm-cleanup.replacepathregex.replacement=/VirtualHostBase/https/testing.pimaker.org/Plone/++api++/VirtualHostRoot/$$3"
        - "traefik.http.middlewares.testing_pimaker-vhm.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.testing_pimaker-vhm.replacepathregex.replacement=/VirtualHostBase/https/testing.pimaker.org/Plone/++api++/VirtualHostRoot/$$1"
        ### Backend ClassicUI VHM
        - "traefik.http.middlewares.testing_pimaker-vhm-classicui.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.testing_pimaker-vhm-classicui.replacepathregex.replacement=/VirtualHostBase/https/testing.pimaker.org/Plone/VirtualHostRoot/_vh_ClassicUI/$$1"
        ### Backend zopeadmin root path
        - "traefik.http.middlewares.testing_pimaker-root-zopeadmin.replacepathregex.regex=^/zopeadmin($$|/.*)"
        - "traefik.http.middlewares.testing_pimaker-root-zopeadmin.replacepathregex.replacement=/VirtualHostBase/https/testing.pimaker.org/VirtualHostRoot/_vh_ClassicUI/manage_main/$$1"

        # ROUTES
        ## testing.pimaker.org API
        - traefik.http.routers.testing_pimaker-backend.rule=Host(`testing.pimaker.org`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.testing_pimaker-backend.entrypoints=websecure
        - traefik.http.routers.testing_pimaker-backend.tls=true
        - traefik.http.routers.testing_pimaker-backend.service=testing_pimaker-backend
        - traefik.http.routers.testing_pimaker-backend.middlewares=gzip,testing_pimaker-vhm-cleanup,testing_pimaker-vhm
        ### testing.pimaker.org /ClassicUI - protected with basic auth (prevent SEOs from crawl it)
        - traefik.http.routers.testing_pimaker-classicui.rule=Host(`testing.pimaker.org`) && (PathPrefix(`/ClassicUI`))
        - traefik.http.routers.testing_pimaker-classicui.entrypoints=websecure
        - traefik.http.routers.testing_pimaker-classicui.tls=true
        - traefik.http.routers.testing_pimaker-classicui.service=testing_pimaker-backend
        - traefik.http.routers.testing_pimaker-classicui.middlewares=gzip,testing_pimaker-backend-auth,testing_pimaker-vhm-classicui
        ### testing.pimaker.org /zope - protected with basic auth (prevent unauthorized acess)
        - traefik.http.routers.testing_pimaker-zopeadmin.rule=Host(`testing.pimaker.org`) && (PathPrefix(`/zopeadmin`))
        - traefik.http.routers.testing_pimaker-zopeadmin.entrypoints=websecure
        - traefik.http.routers.testing_pimaker-zopeadmin.tls=true
        - traefik.http.routers.testing_pimaker-zopeadmin.service=testing_pimaker-backend
        - traefik.http.routers.testing_pimaker-zopeadmin.middlewares=gzip,testing_pimaker-zope-auth,testing_pimaker-root-zopeadmin

networks:
  traefik-public:
    external: true
  traefik-testing_pimaker:
    driver: overlay
