name: Release production CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME_PREFIX: ghcr.io/fosten/plone-pimaker-site
  BACKEND_IMAGE_NAME_SUFFIX: backend
  FRONTEND_IMAGE_NAME_SUFFIX: frontend

jobs:

  meta:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.vars.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set Env Vars
        id: vars
        run: |
          echo "TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  release-frontend:
    runs-on: ubuntu-latest
    needs:
      - meta
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ${{ env.IMAGE_NAME_PREFIX }}-${{ env.FRONTEND_IMAGE_NAME_SUFFIX }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=pep440,pattern={{version}}
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.3.0
        with:
          platforms: linux/amd64
          context: frontend
          file: frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release-backend:
    runs-on: ubuntu-latest
    needs:
      - meta
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ${{ env.IMAGE_NAME_PREFIX }}-${{ env.BACKEND_IMAGE_NAME_SUFFIX }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=pep440,pattern={{version}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.3.0
        with:
          platforms: linux/amd64
          context: backend
          file: backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - meta
      - release-backend
      - release-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Deploy to cluster
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_GHCR_READ_TOKEN }}
          remote_host: ${{ vars.DEPLOY_HOST }}
          remote_port: ${{ vars.DEPLOY_PORT }}
          remote_user: ${{ vars.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: devops/stacks/pimaker.org.yml
          stack_name: pimaker-org
          stack_param: ${{ needs.meta.outputs.TAG }}
          env_file: ${{ secrets.ENV_FILE }}
          deploy_timeout: 480